services:
  comfyui:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    image: comfyui 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
    volumes:
      - "../models/ComfyUI:/ComfyUI/models"
    command: python main.py --listen
